# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsRuL-j3Y_Wdg-JnZywkV47Tv7aDv_DV
"""

import pandas as pd
from sklearn import linear_model
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/homeprices.csv")
df

import math
bed=math.floor(df.bedrooms.median())
bed

df.bedrooms=df.bedrooms.fillna(bed)
df

model=linear_model.LinearRegression()
model.fit(df[["area","bedrooms","age"]],df.price)

from sklearn.model_selection import train_test_split

x=df[["area","bedrooms","age"]]
x

y=df.price
y

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

model.score(X_train,Y_train)